# Generated by Django 3.2.18 on 2023-05-02 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_users_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='img',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
