# Generated by Django 3.2.18 on 2023-05-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customers_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='img',
        ),
    ]
